// File autogenerated by camera_calibration
#ifndef CAMERA_CONSTANTS
#define CAMERA_CONSTANTS

#define CAMERA_WIDTH 640.0 // px
#define CAMERA_HEIGHT 480.0 // px
#define CAMERA_OFFSET 263.0 // mm
#define CAMERA_FIELD_OF_VIEW 75.0 // degrees
#define CAMERA_FOCAL_POINT 1234

#endif
