#include "utils/utils.h"
#include "utils/constants.h"
#include "utils/io_common.h"
#include "lib/ArduinoMock.h"
#include "lib/linux.h"
#include "lib/lib.h"
#include "lib/serial.h"

// ---------------
// ---------------

//#include "lib/draw_matplotlib.h"
//#include "lib/matplotlibcpp.h"
//#include "lib/opencv.h"
//#include "lib/NLTemplate.h"
//#include "lib/hrcode_constants.h"
//#include "lib/hr_code.h"
//#include "helper/logging.h"
//#include "test/test.h"
//#include "core/input_parser.h"
//#include "core/two_way_stream.h"
//#include "core/Motor.h"
//#include "core/writer/console_writer.h"
//#include "core/writer/serial_writer.h"
//#include "core/writer/simulation_writer.h"
//#include "core/writer/stream_writer.h"
//#include "core/writer/writer.h"
//#include "core/writer/std_writer.h"
//#include "core/writer/log_writer.h"
//#include "core/tess_parser.h"
//#include "core/pinpoint.h"
//#include "core/database.h"
//#include "core/Encoder.h"
//#include "core/serialize.h"
//#include "core/recipe_parser.h"
//#include "core/program.h"
//#include "core/parser.h"
//#include "core/heda.h"
//#include "core/referencer.h"
//#include "core/reader/shared_reader.h"
//#include "core/reader/log_reader.h"
//#include "core/reader/fake_reader.h"
//#include "core/reader/serial_reader.h"
//#include "core/reader/io_reader.h"
//#include "core/reader/reader.h"
//#include "core/deserialize.h"
//#include "core/io_program.h"
//#include "core/model.h"
//#include "core/log.h"
//#include "core/position.h"
//#include "core/DCMotor.h"
//#include "core/StepperMotor.h"
//
//#include "core/heda_controller.h"

int main() {
  return 2;
}
